#!/bin/bash

# READ BEFORE EXECUTING:
# Make sure that you know what you're doing when executing this file

if ! command -v php &> /dev/null; then
    echo Installing PHP and Composer

    # Laravel Approach (don't work properly)
    # /bin/bash -c "$(curl -fsSL https://php.new/install/linux/8.4)"

    # Pacman Approach (Arch Linux)
    # sudo pacman -S php composer
fi

read -rsp $'Check if the PHP ini file is with the proper fields.\nPress enter to continue...\n'

# echo Updating composer
composer update

# echo Installing Laravel
# composer global require laravel/installer

# echo Installing vendor
composer install

# echo Generating the .env file
cp .env.example .env
php artisan key:generate

# echo Migrating/Populating the Database
read -rsp $'Check if the SGBD (if required) is ON.\nPress enter to continue...\n'
php artisan migrate

# echo Dealing with Node (installing dependencies and building the application)
read -rsp $'Check if the the latest version of Node.js is installed.\nPress enter to continue...\n'
npm install && npm run build

# echo Running the application
composer run dev

# Installing Breeze

# composer require laravel/breeze --dev

# php artisan breeze:install
